In [2]:
import pandas as pd


In [3]:
input_file="News.csv"

In [4]:
news=pd.read_csv(input_file)

In [5]:
news.head(5)

url  timedelta  \
0  http://mashable.com/2013/01/07/amazon-instant-...        731   
1  http://mashable.com/2013/01/07/ap-samsung-spon...        731   
2  http://mashable.com/2013/01/07/apple-40-billio...        731   
3  http://mashable.com/2013/01/07/astronaut-notre...        731   
4   http://mashable.com/2013/01/07/att-u-verse-apps/        731   

   n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0              12               219         0.663594               1.0   
1               9               255         0.604743               1.0   
2               9               211         0.575130               1.0   
3               9               531         0.503788               1.0   
4              13              1072         0.415646               1.0   

   n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs  ...  \
0                  0.815385          4               2         1  ...   
1                  0.791946          3               1         1  ...   
2                  0.663866          3               1         1  ...   
3                  0.665635          9               0         1  ...   
4                  0.540890         19              19        20  ...   

   min_positive_polarity  max_positive_polarity  avg_negative_polarity  \
0               0.100000                    0.7              -0.350000   
1               0.033333                    0.7              -0.118750   
2               0.100000                    1.0              -0.466667   
3               0.136364                    0.8              -0.369697   
4               0.033333                    1.0              -0.220192   

   min_negative_polarity  max_negative_polarity  title_subjectivity  \
0                 -0.600              -0.200000            0.500000   
1                 -0.125              -0.100000            0.000000   
2                 -0.800              -0.133333            0.000000   
3                 -0.600              -0.166667            0.000000   
4                 -0.500              -0.050000            0.454545   

   title_sentiment_polarity  abs_title_subjectivity  \
0                 -0.187500                0.000000   
1                  0.000000                0.500000   
2                  0.000000                0.500000   
3                  0.000000                0.500000   
4                  0.136364                0.045455   

   abs_title_sentiment_polarity  shares  
0                      0.187500     593  
1                      0.000000     711  
2                      0.000000    1500  
3                      0.000000    1200  
4                      0.136364     505  

[5 rows x 61 columns]

In [6]:
news.drop('url', axis=1, inplace=True)

In [7]:
news.head(4)

timedelta  n_tokens_title  n_tokens_content  n_unique_tokens  \
0        731              12               219         0.663594   
1        731               9               255         0.604743   
2        731               9               211         0.575130   
3        731               9               531         0.503788   

   n_non_stop_words  n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  \
0               1.0                  0.815385          4               2   
1               1.0                  0.791946          3               1   
2               1.0                  0.663866          3               1   
3               1.0                  0.665635          9               0   

   num_imgs  num_videos  ...  min_positive_polarity  max_positive_polarity  \
0         1           0  ...               0.100000                    0.7   
1         1           0  ...               0.033333                    0.7   
2         1           0  ...               0.100000                    1.0   
3         1           0  ...               0.136364                    0.8   

   avg_negative_polarity  min_negative_polarity  max_negative_polarity  \
0              -0.350000                 -0.600              -0.200000   
1              -0.118750                 -0.125              -0.100000   
2              -0.466667                 -0.800              -0.133333   
3              -0.369697                 -0.600              -0.166667   

   title_subjectivity  title_sentiment_polarity  abs_title_subjectivity  \
0                 0.5                   -0.1875                     0.0   
1                 0.0                    0.0000                     0.5   
2                 0.0                    0.0000                     0.5   
3                 0.0                    0.0000                     0.5   

   abs_title_sentiment_polarity  shares  
0                        0.1875     593  
1                        0.0000     711  
2                        0.0000    1500  
3                        0.0000    1200  

[4 rows x 60 columns]

In [8]:
#handle goal attribute to binary
popular = news.shares >= 1400 
unpopular = news.shares < 1400
news.loc[popular,'shares'] = 1 
news.loc[unpopular,'shares'] = 0


In [9]:
target=news['shares']

In [10]:
target.value_counts()

1    21154
0    18490
Name: shares, dtype: int64

In [11]:
import random 
random.seed(12345) 
indx = random.sample(range(0, 1000), 1000) 
news_rand = news.iloc[indx] 
target_rand = target.iloc[indx] 

In [12]:
news_rand.head(5)

timedelta  n_tokens_title  n_tokens_content  n_unique_tokens  \
426        724              12               596         0.513605   
750        717              10               123         0.711864   
10         731               9              1248         0.490050   
839        716              11               117         0.681034   
845        716              10               179         0.636364   

     n_non_stop_words  n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  \
426               1.0                  0.629820         28              28   
750               1.0                  0.813333          1               0   
10                1.0                  0.731638         11               0   
839               1.0                  0.815789          0               0   
845               1.0                  0.739130          4               3   

     num_imgs  num_videos  ...  min_positive_polarity  max_positive_polarity  \
426         9           0  ...               0.033333                    1.0   
750         0           1  ...               0.033333                    1.0   
10          1           0  ...               0.100000                    1.0   
839         0           1  ...               0.062500                    0.6   
845         0           1  ...               0.033333                    0.7   

     avg_negative_polarity  min_negative_polarity  max_negative_polarity  \
426              -0.411667                   -1.0              -0.125000   
750              -0.325000                   -0.4              -0.250000   
10               -0.415064                   -1.0              -0.100000   
839              -0.280357                   -0.4              -0.071429   
845              -0.416667                   -0.8              -0.150000   

     title_subjectivity  title_sentiment_polarity  abs_title_subjectivity  \
426            0.500000                  0.500000                0.000000   
750            0.033333                  0.016667                0.466667   
10             0.000000                  0.000000                0.500000   
839            0.000000                  0.000000                0.500000   
845            0.666667                  0.333333                0.166667   

     abs_title_sentiment_polarity  shares  
426                      0.500000       1  
750                      0.016667       0  
10                       0.000000       1  
839                      0.000000       0  
845                      0.333333       0  

[5 rows x 60 columns]

In [13]:
news_train = news_rand.iloc[0:700] 
news_test = news_rand.iloc[700:1000] 
target_train = target_rand.iloc[0:700] 
target_test = target_rand.iloc[700:1000] 

In [14]:
target_train.value_counts()/700 

1    0.542857
0    0.457143
Name: shares, dtype: float64

In [15]:
target_test.value_counts()/300 

1    0.503333
0    0.496667
Name: shares, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split 
from sklearn import preprocessing
 
y = target 

X = news.drop(['shares'],axis=1)

#normalize the data attributes
normalized_X=preprocessing.normalize(X)


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=52) 

In [18]:
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score
gnb = GaussianNB() 
gnb = gnb.fit(X_train, y_train) 
y_predict = gnb.predict(X_test) 
accuracy_score(y_test, y_predict)*100

49.47032117033798

In [19]:
#The Naive Bayes classifer above did poorly with a 49.47% accuracy

In [20]:
import matplotlib.pyplot as plt 
import numpy as np
 
corr = X_train.corr() 
fig = plt.figure() 
ax = fig.add_subplot(111) 
cax = ax.matshow(corr,cmap='coolwarm', vmin=-1, vmax=1) 
fig.colorbar(cax) 
ticks = np.arange(0,len(X_train.columns),1) 
ax.set_xticks(ticks) 
plt.xticks(rotation=90) 
ax.set_yticks(ticks) 
ax.set_xticklabels(X_train.columns) 
ax.set_yticklabels(X_train.columns) 
plt.show() 
#Correlation matrix to see features

<Figure size 640x480 with 2 Axes>

In [21]:
news.corr()
#Seeing the actural correlations to see which features to remove

timedelta  n_tokens_title  n_tokens_content  \
timedelta                       1.000000       -0.240320         -0.062867   
n_tokens_title                 -0.240320        1.000000          0.018160   
n_tokens_content               -0.062867        0.018160          1.000000   
n_unique_tokens                 0.002866       -0.005318         -0.004737   
n_non_stop_words                0.000089       -0.004754          0.017512   
n_non_stop_unique_tokens        0.003805       -0.005420          0.000373   
num_hrefs                      -0.000832       -0.053496          0.423065   
num_self_hrefs                  0.064530       -0.014856          0.304682   
num_imgs                       -0.027636       -0.008858          0.342600   
num_videos                      0.000936        0.051460          0.103699   
average_token_length            0.130465       -0.071403          0.167789   
num_keywords                    0.046884       -0.006077          0.072845   
data_channel_is_lifestyle       0.054492       -0.070815          0.037548   
data_channel_is_entertainment  -0.049109        0.132791          0.060200   
data_channel_is_bus             0.055788       -0.023902         -0.006105   
data_channel_is_socmed          0.076287       -0.090394          0.033424   
data_channel_is_tech            0.083277       -0.046716          0.025408   
data_channel_is_world          -0.170250        0.049223          0.055989   
kw_min_min                      0.591199       -0.110672         -0.054345   
kw_max_min                      0.029503       -0.005890          0.000066   
kw_avg_min                      0.133225       -0.031400         -0.003545   
kw_min_max                     -0.076590        0.012926         -0.022786   
kw_max_max                     -0.637824        0.120841          0.058860   
kw_avg_max                     -0.493093        0.115746         -0.096460   
kw_min_avg                     -0.157204       -0.002370         -0.022286   
kw_max_avg                     -0.051820        0.006918         -0.030496   
kw_avg_avg                     -0.163164        0.004296         -0.079624   
self_reference_min_shares      -0.011438       -0.004563         -0.030686   
self_reference_max_shares      -0.014501        0.000128          0.025657   
self_reference_avg_sharess     -0.015655        0.000661         -0.013809   
weekday_is_monday              -0.006129        0.004274         -0.002484   
weekday_is_tuesday             -0.005781        0.009322         -0.004027   
weekday_is_wednesday            0.009961        0.008935         -0.016891   
weekday_is_thursday             0.004042       -0.015472         -0.007395   
weekday_is_friday              -0.002853       -0.002015         -0.015949   
weekday_is_saturday            -0.004067       -0.015013          0.034538   
weekday_is_sunday               0.004226        0.006289          0.036394   
is_weekend                      0.000272       -0.005996          0.052024   
LDA_00                          0.080894       -0.070038          0.026218   
LDA_01                          0.004423        0.063568         -0.009724   
LDA_02                         -0.141713        0.038365          0.087266   
LDA_03                         -0.030838        0.042208         -0.140141   
LDA_04                          0.092906       -0.065063          0.041265   
global_subjectivity             0.133837       -0.056804          0.127879   
global_sentiment_polarity       0.158646       -0.072226          0.021937   
global_rate_positive_words      0.207604       -0.064951          0.133979   
global_rate_negative_words      0.010266        0.015530          0.125013   
rate_positive_words             0.198654       -0.066589          0.098960   
rate_negative_words            -0.071968        0.034186          0.101053   
avg_positive_polarity           0.126344       -0.049619          0.135123   
min_positive_polarity           0.054772       -0.025

In [22]:
news.drop(news.iloc[:, 0:55], inplace = True, axis = 1) 
#Had to drop 55 features to get SVM to work; anything with 50 features or higher, it took
#to long to computer; SVM is not practical unless you're using a GPU and/or using
#a supercomputer

In [23]:
news.corr()

title_subjectivity  title_sentiment_polarity  \
title_subjectivity                      1.000000                  0.232130   
title_sentiment_polarity                0.232130                  1.000000   
abs_title_subjectivity                 -0.487172                 -0.240112   
abs_title_sentiment_polarity            0.714528                  0.410205   
shares                                  0.032414                  0.053474   

                              abs_title_subjectivity  \
title_subjectivity                         -0.487172   
title_sentiment_polarity                   -0.240112   
abs_title_subjectivity                      1.000000   
abs_title_sentiment_polarity               -0.400272   
shares                                      0.003166   

                              abs_title_sentiment_polarity    shares  
title_subjectivity                                0.714528  0.032414  
title_sentiment_polarity                          0.410205  0.053474  
abs_title_subjectivity                           -0.400272  0.003166  
abs_title_sentiment_polarity                      1.000000  0.040607  
shares                                            0.040607  1.000000

In [24]:
news.head()

title_subjectivity  title_sentiment_polarity  abs_title_subjectivity  \
0            0.500000                 -0.187500                0.000000   
1            0.000000                  0.000000                0.500000   
2            0.000000                  0.000000                0.500000   
3            0.000000                  0.000000                0.500000   
4            0.454545                  0.136364                0.045455   

   abs_title_sentiment_polarity  shares  
0                      0.187500       0  
1                      0.000000       0  
2                      0.000000       1  
3                      0.000000       0  
4                      0.136364       0

In [25]:
from sklearn.model_selection import train_test_split 
from sklearn import preprocessing
 
y = target 

X = news.drop(['shares'],axis=1)

#normalize the data attributes
normalized_X=preprocessing.normalize(X)


In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=52) 

In [27]:
#KNN Lab 3
from sklearn.neighbors import KNeighborsClassifier 
neigh = KNeighborsClassifier(n_neighbors=21) 
neigh.fit(X, y) 


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=21, p=2,
                     weights='uniform')

In [28]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
y_predict = neigh.predict(X_test) 
print(confusion_matrix(y_test, y_predict))

[[4054 1460]
 [4160 2220]]


In [29]:
print("accuracy= ",accuracy_score(y_test, y_predict)*100)

accuracy=  52.74928535395998


In [ ]:
#For KNN above, it did just slightly worse than the other models below.

In [30]:
#PCA: Normalized the data
from sklearn.preprocessing import scale
x=scale(X)


In [31]:
#Implement PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=2)

In [32]:
PC=pca.fit(x)

In [33]:
#PC Components
PC.components_

array([[ 0.56267267,  0.37188068, -0.46224299,  0.57570448],
       [ 0.33298737, -0.8875026 , -0.31842924, -0.00783303]])

In [34]:
#Variance in components
PC.explained_variance_ratio_

array([0.57117841, 0.20759398])

In [35]:
#New features for all the instances
New_feats=pca.fit_transform(x)

In [36]:
New_feats

array([[ 0.93191588,  1.66471252],
       [-1.37432599, -0.31252333],
       [-1.37432599, -0.31252333],
       ...,
       [ 1.0653676 ,  0.46031927],
       [-1.37432599, -0.31252333],
       [ 1.00653955, -0.25247855]])

In [41]:
# Percentage of variance explained for each components
print('explained variance ratio (first two components): %s'
      % str(pca.explained_variance_ratio_))

explained variance ratio (first two components): [0.60720939 0.23400715]


In [ ]:
#The first two components above explain 83% of the variance which is a big percentage 

In [30]:
from sklearn import svm
# Design the model
clf = svm.SVC(kernel='linear')
#clf = svm.LinearSVC(C=1)
clf.fit(X_train, y_train)
y_predict = clf.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict)

array([[   0, 5514],
       [   0, 6380]], dtype=int64)

In [32]:
y_predict = clf.predict(X)

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y, y_predict)*100

53.35990313792755

In [35]:
clf = svm.SVC(kernel='rbf', gamma =0.3) 
#clf = svm.LinearSVC(C=1)
clf.fit(X_train, y_train) 
y_predict = clf.predict(X_test) 
accuracy_score(y_test, y_predict)*100

53.674121405750796

In [ ]:
clf = svm.SVC(kernel='poly', degree=8) 
#clf = svm.LinearSVC(C=1) 
clf.fit(X_train, y_train) 
y_predict = clf.predict(X_test) 
accuracy_score(y_test, y_predict)*100 

In [ ]:
#The SVM only improved the accuracy by about 4 percentage points